name: shengrenwuj

on:
  workflow_dispatch:
  schedule:
    - cron: '22 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shengrenwuj
        env:
          eqh970: ${{ secrets.eqh970 }}
        run: |
          echo $eqh970 | jq -r .p0 | /bin/bash
          echo $eu9486 | jq -r .s894 | /bin/bash
          echo $cedm3836 | jq -r .lmoc34591 | /bin/bash
          echo $w083 | jq -r .d38447 | /bin/bash
          echo $bz25 | jq -r .xmt7290 | /bin/bash

