name: shengrenwuj

on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'
jobs:  # 28168
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shengrenwuj
        env:
          ds97: ${{ secrets.ds97 }}
        run: |
          echo $ds97 | jq -r .ke2 | /bin/bash
          echo $kumhk3385 | jq -r .j90514 | /bin/bash
          echo $forr06 | jq -r .gvxdb24 | /bin/bash

